marks = []
f1 = input("Enter Marks : ")
marks.append(f1)
f2 = input("Enter Marks : ")
marks.append(f2)
f2 = input("Enter Marks : ")
marks.append(f2)
f3 = input("Enter Marks : ")
marks.append(f3)
f4 = input("Enter Marks : ")
marks.append(f4)
f5 = input("Enter Marks : ")
marks.append(f5)
f6 = input("Enter Marks : ")
marks.append(f6)

marks.sort()
print(marks)
