s = set()
n = int(input("Enter the first number:"))
s.add(int(n))
n = int(input("Enter the second number:"))
s.add(int(n))
n = int(input("Enter the third number:"))
s.add(int(n))
n = int(input("Enter the fourth number:"))
s.add(int(n))
n = int(input("Enter the fifth number:"))
s.add(int(n))
n = int(input("Enter the sixth number:"))
s.add(int(n))
n = int(input("Enter the seventh number:"))
s.add(int(n))
n = int(input("Enter the eight number:"))
s.add(int(n))

print(s)

